# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Felipe Barbosa - Negócios, Marketing & Produto
  avatar: felipe-barbosa-business-marketing-product-growth.png
  gravatar: # Email MD5 hash
  description: "Um blog para falar sobre negócios de tecnologia, marketing nas startups (growth marketing) e desenvolvimento de produto." # used by search engines

  # Header and footer text
  header_text: >
    <p>Quer receber dicas de livros, artigos interessantes e posts novos do blog?</p>
    <div id="mlb2-5388423" class="ml-subscribe-form ml-subscribe-form-5388423">
    <div class="ml-vertical-align-center">
    <div class="subscribe-form ml-block-success" style="display:none">
        <div class="form-section">
            <p>Thank you! You have successfully subscribed to our newsletter.</p>
        </div>
    </div>
    <form class="ml-block-form" action="//app.mailerlite.com/webforms/submit/t2x4q0" data-id="457995" data-code="t2x4q0" method="POST" target="_blank">
        <div class="subscribe-form horizontal">
            <div class="form-section horizontal">
                <div class="form-group ml-field-name ml-validate-required">
                    <input type="text" name="fields[name]" class="form-control" placeholder="Name*" value="" autocomplete="name" x-autocompletetype="name" spellcheck="false" autocapitalize="off" autocorrect="off">
                </div>
                <div class="form-group ml-field-email ml-validate-required ml-validate-email">
                    <input type="email" name="fields[email]" class="form-control" placeholder="Email*" value="" autocomplete="email" x-autocompletetype="email" spellcheck="false" autocapitalize="off" autocorrect="off">
                </div>
            </div>
            <div class="form-section horizontal ml-button-position">
                <button type="submit" class="primary">
                    Sim, eu quero!
                </button>
                <button disabled="disabled" style="display: none;" type="button" class="loading">
                    <img src="//static.mailerlite.com/images/rolling.gif" width="20" height="20" style="width: 20px; height: 20px;">
                </button>
            </div>
            <div class="clearfix" style="clear: both;"></div>
            <input type="hidden" name="ml-submit" value="1" />
        </div>
    </form>     
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "felipecbarbosa"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/felipecardosobarbosa/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "felipecb_"
  medium: "felipe-barbosa"
  youtube:

  # Scripts
  disqus_shortname: felipebarbosa
    
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag]
