# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://felipebarbosa.me" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Felipe Barbosa
  avatar: felipe_barbosa-logo-icon-alternative.png
  gravatar: # Email MD5 hash
  description: "Um blog para falar sobre Negócios de Tecnologia, Marketing e Desenvolvimento de Produto." # used by search engines
  author: Felipe Barbosa
  name: Felipe Barbosa
  locale: pt-br
  image: https://res.cloudinary.com/felipe-barbosa/image/upload/v1677281551/Brand%20Assets/social-image-og-alternative.png
  
  # Header and footer text
  header_text: >
    <h2 style="color: #ffffff; font-size: 1.2em; background: linear-gradient(-70deg, #ffffff 0%, #0099ff 100%, transparent); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">Marketing & Product & Growth</h2>
    <!-- a class="button" style="color: #ffffff; background-color: #0099ff;" onclick="analytics.track('clicked-curadoria-button') "href="https://curadoria.felipebarbosa.me/" target="_blank">CONHEÇA E ASSINE!</a -->
        
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> and <a href="https://pages.github.com/">Github Pages</a><br>Felipe Barbosa 2022

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "felipecbarbosa"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/felipecardosobarbosa/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  ideas: # https://portal.prodpad.com/b80a11cc-6d54-11e7-9642-22000a2145da
  cv: 
  twitter: "felipecb_"
  medium: https://www.felipebarbosa.me/medium/
  ajuda: # https://ajuda.felipebarbosa.me/

  # Scripts
  disqus_shortname: # felipebarbosa
  search: false # Enable the search feature
    
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  str_download: "Faça o download do meu"
  str_ideas: "Deixe sua"
  str_ajuda: "Precisa de"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-sitemap, jekyll-redirect-from]
