# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Felipe Barbosa - Negócios, Marketing & Produto
  avatar: felipe-barbosa-business-marketing-product-growth.png
  gravatar: # Email MD5 hash
  description: "Um blog para falar sobre negócios de tecnologia, marketing nas startups (growth marketing) e desenvolvimento de produto." # used by search engines
  author:
  name: Felipe Barbosa
  twitter: 'felipecb_'
  locale: pt-br
  
  # Header and footer text
  header_text: >
    <p>Quer receber dicas de livros, artigos interessantes e posts novos do blog?</p>
        
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "felipecbarbosa"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/felipecardosobarbosa/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "felipecb_"
  medium: "felipe-barbosa"
  youtube:

  # Scripts
  disqus_shortname: felipebarbosa
    
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-sitemap]
