# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://felipebarbosa.me" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Felipe Barbosa
  avatar: felipe-barbosa-business-marketing-product-growth.png
  gravatar: # Email MD5 hash
  description: "Um blog para falar sobre negócios de tecnologia, marketing nas startups (growth marketing) e desenvolvimento de produto." # used by search engines
  author: Felipe Barbosa
  name: Felipe Barbosa
  locale: pt-br
  image: https://res.cloudinary.com/felipe-barbosa/image/upload/q_100/v1498795725/social-img-og.png
  
  # Header and footer text
  header_text: >
    <p style="color: #0099ff;">Quer receber dicas de livros, de artigos e posts novos do blog?</p>
    <div id="mc_embed_signup_header">
    <form action="//felipebarbosa.us11.list-manage.com/subscribe/post?u=d761afe0b6c97e9f4579c61bf&amp;id=4844c62c9d" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form-header" class="validate" target="_blank" novalidate>
        <div id="mc_embed_signup_scroll">
        <input type="email" value="" name="EMAIL" class="email" id="mce-EMAILH" placeholder="Seu melhor email" required>
        <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
        <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_d761afe0b6c97e9f4579c61bf_4844c62c9d" tabindex="-1" value=""></div>
        <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
        </div>
    </form>
    </div>
        
  header_text_feature_image:
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> and <a href="https://pages.github.com/">Github Pages</a><br>Felipe Barbosa 2019

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "felipecbarbosa"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/felipecardosobarbosa/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  ideas: https://portal.prodpad.com/b80a11cc-6d54-11e7-9642-22000a2145da
  cv: "felipe_cv.pdf"
  twitter: "felipecb_"
  medium: "felipe-barbosa"
  youtube:

  # Scripts
  disqus_shortname: felipebarbosa
    
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  str_download: "Faça o download do meu"
  str_ideas: "Deixe sua"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate, jekyll-sitemap]
